server:
  port: 8007
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 139.129.93.162:8848
        namespace: dev
    gateway:
      routes:
        - id: gateway1
          uri: http://127.0.0.1:8070
          predicates:
            - Path=/c_nacos/info
        - id: gateway2
          uri: http://www.baidu.com
          predicates:
            - Path=/
        - id: lb_gateway
          uri: lb://client1
          predicates:
            - Path=/nacos/info,/nacos/discovery
            - After=2021-04-19T16:03:43.706+08:00[Asia/Shanghai]

