server:
  port: 8888
spring:
  application:
    name: boot-log
  boot:
    admin:
      client:
        url: http://127.0.0.1:8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
